# Site settings
title: petebachant.me
email: petebachant@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My personal website.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://petebachant.me" # the base hostname & protocol for your site
twitter_username: petebachant
github_username:  petebachant

# Build settings
markdown: kramdown

kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  use_coderay: false
