# Site settings
title: petebachant.me
include: ["_pages"]
email: petebachant@gmail.com
description: My personal website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://petebachant.me" # the base hostname & protocol for your site
twitter_username: petebachant
github_username:  petebachant
permalink: /:title/

markdown: kramdown
highlighter: rouge

gems:
  - jekyll-redirect-from
  - jekyll-paginate

paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: Projects
   url: /projects
 - title: Wiki
   url: https://github.com/petebachant/petebachant.github.io/wiki

social:
   github: petebachant
   twitter: petebachant
   email: petebachant@gmail.com

# google_analytics: "UA-58263416-1"
